import Foundation
import CoreLocation

enum ThermalSource {
    case real        // detected from actual flight (persistent across sim on/off)
    case simulated   // generated by FlightSimulator (cleared when sim stops)
}

struct ThermalPoint: Identifiable, Equatable {
    let id = UUID()
    let coordinate: CLLocationCoordinate2D
    let altitude: Double        // m
    let strength: Double        // m/s average climb
    let timestamp: Date
    var source: ThermalSource = .real

    static func == (lhs: ThermalPoint, rhs: ThermalPoint) -> Bool {
        lhs.id == rhs.id
    }
}
